apiVersion: apps/v1
kind: Deployment
metadata:
  name: btprocesspensionapi-deployment
  labels:
    app: BTProcessPensionAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BTProcessPensionAPI
  template:
    metadata:
      labels:
        app: BTProcessPensionAPI
    spec:
      containers:
      - name: btprocesspensionapi
        image: btprojcr.azurecr.io/btprocesspensionimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: btpmsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: btprocesspensionapisvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector: 
    app: BTProcessPensionAPI